# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: FreedomGram

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: gh0stier/kbe

    steps:
    - uses: actions/checkout@v2
    - name: Updating Build Environment
      run: |
        sudo apt update
        sudo apt upgrade
        sudo full-upgrade
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Building for Android platform
      run: |
        pip install --upgrade Cython==0.29.19 virtualenv
        #Updating buildozer
        git clone https://github.com/kivy/buildozer.git
        cd buildozer
        sudo python setup.py install
        cd ..
        sudo rm -rf buildozer
        # building app for android platform
        buildozer -v android debug
        mkdir outing
        cp bin/* outing
    - uses: actions/upload-artifact@v2
      with:
        name: out-artifacts
        path: outing
